spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:50846/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: FbCWXnYPKSZIGRlDkdPATpRtHfmiKLAD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
